import { StyleSheet, Dimensions } from 'react-native';
const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f0f2f7', position: 'relative' },

  // HEADER - Enhanced with gradient background
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 18,
    backgroundColor: '#1a2f4d',
    elevation: 10,
    shadowColor: '#0d1a2f',
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    marginBottom: 0,
    position: 'relative',
  },
  headerGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 0,
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    zIndex: 1,
  },
  dashboardText: { fontSize: 28, fontWeight: '800', color: '#fff', letterSpacing: 0.5 },
  greetingText: { fontSize: 14, color: '#d0dfe8', marginTop: 4, fontWeight: '500' },

  // BELL - Enhanced notification icon
  bellContainer: {
    backgroundColor: '#FFD700',
    borderRadius: 10,
    padding: 5,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
    shadowColor: '#FFD700',
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
  },
  badge: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: '#FF4444',
    width: 22,
    height: 22,
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
    elevation: 3,
    shadowColor: '#FF4444',
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  badgeText: { color: '#fff', fontSize: 10, fontWeight: '900' },

  // TOP CARDS - Premium styling
  topRow: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    paddingHorizontal: 16, 
    marginBottom: 22,
    marginTop: 18,
  },
  card: { 
    width: (width - 48) / 2, 
    borderRadius: 24, 
    overflow: 'hidden',
    elevation: 8,
    shadowColor: '#000',
    shadowOpacity: 0.16,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
  },
  fullWidthCard: { 
    width: width - 32, 
    borderRadius: 24, 
    overflow: 'hidden', 
    alignSelf: 'center', 
    marginBottom: 22,
    elevation: 8,
    shadowColor: '#000',
    shadowOpacity: 0.16,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
  },
  gradientCard: { 
    padding: 22, 
    alignItems: 'center', 
    justifyContent: 'center', 
    position: 'relative', 
    height: 150,
    borderRadius: 24,
  },
  bubble1: { 
    position: 'absolute', 
    width: 100, 
    height: 100, 
    backgroundColor: 'rgba(255,255,255,0.35)', 
    borderRadius: 60, 
    top: -40, 
    right: -40 
  },
  bubble2: { 
    position: 'absolute', 
    width: 70, 
    height: 70, 
    backgroundColor: 'rgba(255,255,255,0.25)', 
    borderRadius: 45, 
    bottom: -30, 
    left: -30 
  },
  amountTextWhite: { fontSize: 32, fontWeight: '900', color: '#fff', marginTop: 10, letterSpacing: 0.6 },
  labelTextWhite: { fontSize: 14, color: '#e8f0f7', marginTop: 8, fontWeight: '700', letterSpacing: 0.3 },
  // BANNER - Removed (discount banner)
  bannerContainer: { height: 0, display: 'none' },
  bannerImage: { height: 0, display: 'none' },

  // LEADERBOARD CONTAINER - Modern styling
  leaderboardWrapper: {
    height: height * 0.72,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 24,
    marginTop: 0,
    overflow: 'hidden',
    backgroundColor: '#fff',
    elevation: 12,
    shadowColor: '#0d1a2f',
    shadowOpacity: 0.18,
    shadowOffset: { width: 0, height: -8 },
    shadowRadius: 16,
    position: 'relative',
  },
  leaderboardBackgroundGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    zIndex: 0,
  },
  leaderboardContent: {
    flex: 1,
    zIndex: 1,
  },
  leaderboardWrapperExpanded: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    height: '100%',
    marginTop: 0,
    borderRadius: 0,
    zIndex: 10,
    paddingTop: 50,
  },
  leaderboardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
    paddingHorizontal: 4,
  },
  expandButton: {
    padding: 10,
    borderRadius: 14,
    backgroundColor: '#FFF3CD',
    elevation: 2,
  },
  leaderboardBubbles1: {
    position: 'absolute',
    width: 200,
    height: 200,
    backgroundColor: 'rgba(26, 47, 77, 0.08)',
    borderRadius: 100,
    top: -60,
    right: -60,
    zIndex: 0,
  },
  leaderboardBubbles2: {
    position: 'absolute',
    width: 120,
    height: 120,
    backgroundColor: 'rgba(102, 126, 234, 0.06)',
    borderRadius: 60,
    bottom: -40,
    left: -40,
    zIndex: 0,
  },
  leaderboardScroll: { 
    marginTop: 12, 
    paddingHorizontal: 4,
    paddingBottom: 20,
  },

  leaderboardTitle: { 
    fontSize: 28, 
    fontWeight: '900', 
    color: '#1a2f4d',
    letterSpacing: 0.4,
    lineHeight: 34,
  },

  // PREMIUM BANNER - Eye-catching design
  premiumBanner: {
    backgroundColor: '#FFF8DC',
    borderRadius: 18,
    padding: 24,
    marginBottom: 20,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFD700',
    elevation: 6,
    shadowColor: '#FFD700',
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
  },
  premiumBannerTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1a1a1a',
    marginTop: 12,
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  premiumBannerSubtitle: {
    fontSize: 14,
    color: '#555',
    marginBottom: 16,
    textAlign: 'center',
    fontWeight: '500',
  },
  premiumBannerButton: {
    backgroundColor: '#FFD700',
    paddingHorizontal: 36,
    paddingVertical: 14,
    borderRadius: 14,
    elevation: 5,
    shadowColor: '#FFD700',
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
  },
  premiumBannerButtonText: {
    color: '#1a1a1a',
    fontWeight: '800',
    fontSize: 16,
    letterSpacing: 0.3,
  },

  // LEADERBOARD CARD - Modern card design
  leaderboardCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f7fb',
    borderRadius: 18,
    padding: 18,
    marginBottom: 16,
    elevation: 3,
    shadowColor: '#0d1a2f',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
    borderLeftWidth: 5,
    borderLeftColor: '#667eea',
  },
  firstCardHighlight: { 
    backgroundColor: '#FFF9E6',
    borderLeftColor: '#FFD700',
    elevation: 5,
    borderBottomWidth: 2,
    borderBottomColor: '#FFD700',
    shadowColor: '#FFD700',
    shadowOpacity: 0.15,
  },
  rankIcon: { 
    width: 52, 
    height: 52,
    alignItems: 'center', 
    justifyContent: 'center',
    marginRight: 14,
    backgroundColor: '#e8eff8',
    borderRadius: 26,
    minWidth: 52,
    fontWeight: '800',
    elevation: 3,
    shadowColor: '#667eea',
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  profilePicture: { 
    width: 50, 
    height: 50, 
    borderRadius: 25, 
    marginRight: 14,
    borderWidth: 3,
    borderColor: '#667eea',
    elevation: 3,
    shadowColor: '#667eea',
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
  },
  nameText: { 
    fontSize: 16, 
    color: '#1a2f4d', 
    fontWeight: '800',
    letterSpacing: 0.2,
    flex: 1,
  },
  firstNameHighlight: { 
    color: '#FFD700', 
    fontWeight: '900',
    fontSize: 16,
  },
  pointsBadge: { 
    marginLeft: 'auto',
    backgroundColor: '#667eea',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
    elevation: 4,
    shadowColor: '#667eea',
    shadowOpacity: 0.35,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
  },
  pointsText: { 
    color: '#FFD700', 
    fontWeight: '900',
    fontSize: 18,
    letterSpacing: 0.3,
  },

  // CARD BUBBLES
  cardBubble1: {
    position: 'absolute',
    width: 80,
    height: 80,
    backgroundColor: 'rgba(102, 126, 234, 0.12)',
    borderRadius: 40,
    top: -20,
    right: -20,
  },
  // cardBubble2: {
  //   position: 'absolute',
  //   width: 50,
  //   height: 50,
  //   backgroundColor: 'rgba(26, 47, 77, 0.08)',
  //   borderRadius: 25,
  //   bottom: -15,
  //   left: -15,
  // },  
  sectionTitle: { fontSize: 20, fontWeight: '800', color: '#fff', marginBottom: 10 },

  blurOverlay: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 28,
    zIndex: 2,
  },

  premiumOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 3,
    paddingHorizontal: 20,
  },

  premiumText: { color: '#fff', fontSize: 26, fontWeight: '800', marginBottom: 8, letterSpacing: 0.3 },
  premiumSubText: { color: '#fff', fontSize: 16, marginBottom: 18, fontWeight: '500' },
  premiumButton: {
    backgroundColor: '#1f3a5f',
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: 20,
    elevation: 4,
  },
  premiumButtonText: { color: '#1f3a5f', fontWeight: '800', fontSize: 16, letterSpacing: 0.2 },

});
