import { StyleSheet, Dimensions } from 'react-native';

const { height, width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  headerContainer: {
    width: '100%',
    height: height * 0.2,
    backgroundColor: '#1a2f4d',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  // profileIcon: {
  //   width: 80,
  //   height: 80,
  //   borderRadius: 40,
  //   backgroundColor: '#8e44ad',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   marginRight: 120,
  // },
  profileInfo: {
    flexDirection: 'column',
    paddingLeft: 80,
  },
  nameText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  workerId: {
    color: '#fff',
    fontSize: 14,
    marginBottom: 4,
  },
  ratingText: {
    color: '#fff',
    fontSize: 14,
  },
  contentContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: {
    fontSize: 16,
    color: '#333',
  },
  // Add these below existing styles
cardsRow: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  width: '90%',
  alignSelf: 'center',
  marginTop: 20,
},
profileCard: {
  width: '30%',
  backgroundColor: '#fff',
  borderRadius: 15,
  paddingVertical: 20,
  justifyContent: 'center',
  alignItems: 'center',
  elevation: 3,
  shadowColor: '#000',
  shadowOpacity: 0.1,
  shadowOffset: { width: 0, height: 2 },
  shadowRadius: 4,
},
cardTitle: {
  fontSize: 14,
  fontWeight: '600',
  color: '#333',
  marginTop: 8,
  textAlign: 'center',
},
// Referral Bonus container
referralContainer: {
  width: '100%',
  height: 100,
  backgroundColor: '#fff',
  marginTop: 20,
  paddingHorizontal: 20,
  borderRadius: 15,
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  elevation: 3,
  shadowColor: '#000',
  shadowOpacity: 0.1,
  shadowOffset: { width: 0, height: 2 },
  shadowRadius: 4,
},
referralTextContainer: {
  flexDirection: 'column',
  maxWidth: '70%',
},
referralHeading: {
  fontSize: 16,
  fontWeight: '700',
  color: '#333',
},
referralText: {
  fontSize: 14,
  color: '#777',
  marginTop: 4,
},
// Support container
supportContainer: {
  width: '100%',
  backgroundColor: '#fff',
  marginTop: 20,
  borderRadius: 15,
  padding: 20,
  elevation: 3,
  shadowColor: '#000',
  shadowOpacity: 0.1,
  shadowOffset: { width: 0, height: 2 },
  shadowRadius: 4,
},
supportHeader: {
  fontSize: 16,
  fontWeight: '700',
  color: '#333',
  marginBottom: 15,
},
supportOption: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  paddingVertical: 15,
  borderBottomWidth: 0.5,
  borderBottomColor: '#ddd',
},
supportText: {
  fontSize: 14,
  fontWeight: '600',
  color: '#1a2f4d',
},
headerWithIcon: {
  flexDirection: 'row',
  alignItems: 'center',
  marginBottom: 15,
},
logoutButton: {
  flexDirection: 'row',       // icon + text in a row
  alignItems: 'center',
  justifyContent: 'center',
  width: '90%',               // full width with some margin
  alignSelf: 'center',
  marginTop: 20,
  marginBottom: 20,
  paddingVertical: 14,
  backgroundColor: '#e74c3c', // red color for logout
  borderRadius: 25,
  elevation: 3,
  shadowColor: '#000',
  shadowOpacity: 0.2,
  shadowOffset: { width: 0, height: 2 },
  shadowRadius: 4,
},
logoutText: {
  color: '#fff',
  fontSize: 16,
  fontWeight: '700',
},

profileIcon: {
  width: 100,
  height: 100,
  borderRadius: 50,
  borderWidth: 2,
  borderColor: "#fff",
  overflow: "hidden",
  justifyContent: "center",
  alignItems: "center",
  marginBottom: 10,
},
profilePhoto: {
  width: "100%",
  height: "100%",
  resizeMode: "cover",
},

// Earnings Modal Styles
modalBackdrop: {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: 'rgba(0, 0, 0, 0)',
  zIndex: -1,
},
modalBackdropActive: {
  backgroundColor: 'rgba(0, 0, 0, 0.5)',
  zIndex: 999,
},
earningsModal: {
  position: 'absolute',
  bottom: 0,
  left: 0,
  right: 0,
  maxHeight: height * 0.85,
  backgroundColor: '#f5f5f5',
  borderTopLeftRadius: 25,
  borderTopRightRadius: 25,
  opacity: 0,
  elevation: 10,
  zIndex: 1000,
},
earningsHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  paddingHorizontal: 20,
  paddingVertical: 16,
  backgroundColor: '#1a2f4d',
  borderTopLeftRadius: 25,
  borderTopRightRadius: 25,
},
earningsTitle: {
  fontSize: 20,
  fontWeight: '700',
  color: '#fff',
},
earningsContent: {
  flex: 1,
  paddingHorizontal: 16,
  paddingVertical: 12,
},
totalEarningsCard: {
  borderRadius: 15,
  padding: 20,
  marginBottom: 16,
  justifyContent: 'center',
  alignItems: 'center',
},
totalEarningsLabel: {
  fontSize: 14,
  color: 'rgba(255, 255, 255, 0.8)',
  marginBottom: 8,
},
totalEarningsValue: {
  fontSize: 32,
  fontWeight: '700',
  color: '#fff',
  marginBottom: 4,
},
totalEarningsSubtext: {
  fontSize: 12,
  color: 'rgba(255, 255, 255, 0.7)',
},
earningsBreakdown: {
  backgroundColor: '#fff',
  borderRadius: 15,
  overflow: 'hidden',
  marginBottom: 16,
  elevation: 2,
  shadowColor: '#000',
  shadowOpacity: 0.08,
  shadowOffset: { width: 0, height: 2 },
  shadowRadius: 4,
},
earningsItem: {
  flexDirection: 'row',
  alignItems: 'center',
  paddingHorizontal: 16,
  paddingVertical: 16,
  borderBottomWidth: 1,
  borderBottomColor: '#f0f0f0',
},
earningsIconBox: {
  width: 50,
  height: 50,
  borderRadius: 12,
  justifyContent: 'center',
  alignItems: 'center',
  marginRight: 14,
},
earningsItemContent: {
  flex: 1,
  justifyContent: 'center',
},
earningsItemLabel: {
  fontSize: 13,
  color: '#666',
  marginBottom: 4,
  fontWeight: '500',
},
earningsItemValue: {
  fontSize: 16,
  fontWeight: '700',
  color: '#27AE60',
},
netEarningsCard: {
  backgroundColor: '#fff',
  borderRadius: 15,
  padding: 20,
  alignItems: 'center',
  marginBottom: 20,
  elevation: 2,
  shadowColor: '#000',
  shadowOpacity: 0.08,
  shadowOffset: { width: 0, height: 2 },
  shadowRadius: 4,
},
netEarningsLabel: {
  fontSize: 13,
  color: '#999',
  marginBottom: 8,
  fontWeight: '500',
},
netEarningsValue: {
  fontSize: 28,
  fontWeight: '700',
  color: '#27AE60',
  marginBottom: 14,
},
withdrawButton: {
  flexDirection: 'row',
  backgroundColor: '#27AE60',
  paddingHorizontal: 24,
  paddingVertical: 12,
  borderRadius: 10,
  alignItems: 'center',
  gap: 8,
  width: '100%',
  justifyContent: 'center',
},
withdrawButtonText: {
  color: '#fff',
  fontWeight: '600',
  fontSize: 14,
},

});
